export const Cities = [
  'Amsterdam, Netherlands',
  'London, United Kingdom',
  'Berlin, Germany',
  'Madrid, Spain',
  'Rome, Italy',
  'Paris, France',
  'Bucharest, Romania',
  'Budapest, Hungary',
  'Hamburg, Germany',
  'Warsaw, Poland',
  'Vienna, Austria',
  'Barcelona, Spain',
  'Stockholm, Sweden',
  'Kharkiv, Ukraine',
  'Munich, Germany',
  'Milan, Italy',
  'Kyiv, Ukraine',
  'Prague, Czech Republic',
  'Copenhagen, Denmark',
  'Minsk, Belarus',
  'Sofia, Bulgaria',
  'Dnipro, Ukraine',
  'Donetsk, Ukraine',
  'Dublin, Ireland',
  'Brussels, Belgium',
  'Volgograd, Russia',
  'Odessa, Ukraine',
  'Birmingham, United Kingdom',
  'Perm, Russia',
  'Koeln, Germany',
  'Naples, Italy',
  'Krasnoyarsk, Russia',
  'Turin, Italy',
  'Liverpool, United Kingdom',
  'Saratov, Russia',
  'Voronezh, Russia',
  'Valencia, Spain',
  'Zaporizhia, Ukraine',
  'Marseille, France',
  'Lodz, Poland',
  'Krakow, Poland',
  'Riga, Latvia',
  'Nottingham, United Kingdom',
  'Lviv, Ukraine',
  'Sevilla, Spain',
  "Tol'yatti, Russia",
  'Zagreb, Croatia',
  'Sarajevo, Bosnia and Herzegovina',
  'Sheffield, United Kingdom',
  'Zaragoza, Spain',
  'Athens, Greece',
  'Kryvyi Rih, Ukraine',
  'Frankfurt am Main, Germany',
  'Krasnodar, Russia',
  'Palermo, Italy',
  'Ulyanovsk, Russia',
  'Chisinau, Moldova',
  'Wroclaw, Poland',
  'Izhevsk, Russia',
  'Bristol, United Kingdom',
  'Yaroslavl, Russia',
  'Barnaul, Russia',
  'Rotterdam, Netherlands',
  'Essen, Germany',
  'Glasgow, United Kingdom',
  'Stuttgart, Germany',
  'Dortmund, Germany',
  'Vladivostok, Russia',
  'Irkutsk, Russia',
  'Genoa, Italy',
  'Oslo, Norway',
  'Khabarovsk, Russia',
  'Khabarovsk Vtoroy, Russia',
  'Duesseldorf, Germany',
  'Goeteborg, Sweden',
  'Poznan, Poland',
  'Malaga, Spain',
  'Helsinki, Finland',
  'Orenburg, Russia',
  'Pristina, Kosovo',
  'Bremen, Germany',
  'Vilnius, Lithuania',
  'Novokuznetsk, Russia',
  "Ryazan', Russia",
  'Tyumen, Russia',
  'Lisbon, Portugal',
  'Lipetsk, Russia',
  'Hannover, Germany',
  'Penza, Russia',
  'Mykolayiv, Ukraine',
  'Naberezhnyye Chelny, Russia',
  'Leicester, United Kingdom',
  'Leipzig, Germany',
  'Kalininskiy, Russia',
  'Duisburg, Germany',
  'Astrakhan, Russia',
  'Nuernberg, Germany',
  'Makhachkala, Russia',
  'Dresden, Germany',
  'Tomsk, Russia',
  'Mariupol, Ukraine',
  'Gomel, Belarus',
  'Kemerovo, Russia',
  'Skopje, North Macedonia',
  'The Hague, Netherlands',
  'Lyon, France',
  'Tula, Russia',
  'Edinburgh, United Kingdom',
  'Gdansk, Poland',
  'Antwerpen, Belgium',
  'Kirov, Russia',
  'Leeds, United Kingdom',
  'Luhansk, Ukraine',
  'Cardiff, United Kingdom',
  'Cheboksary, Russia',
  'Murcia, Spain',
  'Kaliningrad, Russia',
  'Toulouse, France',
  'Bryansk, Russia',
  'Bratislava, Slovakia',
  'Moscow, Russia',
  'Ivanovo, Russia',
  'Sevastopol, Ukraine',
  'Magnitogorsk, Russia',
  'Wandsbek, Germany',
  'Kursk, Russia',
  'Szczecin, Poland',
  'Palma, Spain',
  'Tver, Russia',
  'Khmelnytskyi, Ukraine',
  'Manchester, United Kingdom',
  'Tallinn, Estonia',
  'Bochum, Germany',
  'Sector 3, Romania',
  'Las Palmas de Gran Canaria, Spain',
  'Nizhny Tagil, Russia',
  'Bochum-Hordel, Germany',
  'Makiyivka, Ukraine',
  'Tirana, Albania',
  'Kaunas, Lithuania',
  'Stoke-on-Trent, United Kingdom',
  'Brno, Czech Republic',
  'Mahilyow, Belarus',
  'Sector 6, Romania',
  'Bydgoszcz, Poland',
  'Bologna, Italy',
  "Stavropol', Russia",
  'Wuppertal, Germany',
  'Ulan-Ude, Russia',
  'Lublin, Poland',
  'Coventry, United Kingdom',
  "Arkhangel'sk, Russia",
  'Bilbao, Spain',
  'Thessaloniki, Greece',
  'Vinnytsia, Ukraine',
  'Florence, Italy',
  'Sector 2, Romania',
  'Belgorod, Russia',
  'Kurgan, Russia',
  'Vitebsk, Belarus',
  'Zurich, Switzerland',
  'Plovdiv, Bulgaria',
  'Kaluga, Russia',
  'Nice, France',
  'Krasnogvargeisky, Russia',
  'Simferopol, Ukraine',
  'Sunderland, United Kingdom',
  'Alicante, Spain',
  'Bielefeld, Germany',
  'Cordoba, Spain',
  'Sochi, Russia',
  'Birkenhead, United Kingdom',
  'Orel, Russia',
  'Volzhskiy, Russia',
  'Smolensk, Russia',
  'Kherson, Ukraine',
  'Murmansk, Russia',
  'Islington, United Kingdom',
  'Reading, United Kingdom',
  'Iasi, Romania',
  'Valladolid, Spain',
  'Poltava, Ukraine',
  'Vladikavkaz, Russia',
  'Hrodna, Belarus',
  'Katowice, Poland',
  'Cluj-Napoca, Romania',
  'Cherepovets, Russia',
  'Timisoara, Romania',
  'Vologda, Russia',
  'Kingston upon Hull, United Kingdom',
  'Preston, United Kingdom',
  'Bonn, Germany',
  'Ostrava, Czech Republic',
  'Varna, Bulgaria',
  'Vladimir, Russia',
  'Chita, Russia',
  'Mannheim, Germany',
  'Chernihiv, Ukraine',
  'Newport, United Kingdom',
  'Craiova, Romania',
  'Constanta, Romania',
  'Saransk, Russia',
  'Malmoe, Sweden',
  'Brest, Belarus',
  'Surgut, Russia',
  'Swansea, United Kingdom',
  'Bradford, United Kingdom',
  'Cherkasy, Ukraine',
  'Vigo, Spain',
  'Southend-on-Sea, United Kingdom',
  'Sumy, Ukraine',
  'Galati, Romania',
  'Bialystok, Poland',
  'Tambov, Russia',
  'Catania, Italy',
  'Utrecht, Netherlands',
  'Sector 4, Romania',
  'Marienthal, Germany',
  'Karlsruhe, Germany',
  'Zhytomyr, Ukraine',
  'Hamburg-Nord, Germany',
  'Yoshkar-Ola, Russia',
  'Taganrog, Russia',
  'Horlivka, Ukraine',
  'Kostroma, Russia',
  'Gijon, Spain',
  'Bari, Italy',
  'Nantes, France',
  'Brasov, Romania',
  'Komsomolsk-on-Amur, Russia',
  'Strasbourg, France',
  'Belfast, United Kingdom',
  "Nal'chik, Russia",
  'Wiesbaden, Germany',
  'Ljubljana, Slovenia',
  'Sector 5, Romania',
  'Derby, United Kingdom',
  'Muenster, Germany',
  'Gelsenkirchen, Germany',
  'Sterlitamak, Russia',
  'Eixample, Spain',
  'Aachen, Germany',
  'Petrozavodsk, Russia',
  'Moenchengladbach, Germany',
  'Plymouth, United Kingdom',
  'Novosibirsk, Russia',
  'Yekaterinburg, Russia',
  'Nizhniy Novgorod, Russia',
  'Belgrade, Serbia',
  'Augsburg, Germany',
  'Luton, United Kingdom',
  "L'Hospitalet de Llobregat, Spain",
  'Espoo, Finland',
  'Latina, Spain',
  'Bratsk, Russia',
  'Rivne, Ukraine',
  'Gdynia, Poland',
  'Carabanchel, Spain',
  'Wolverhampton, United Kingdom',
  'Eimsbuettel, Germany',
  'Samara, Russia',
  'Omsk, Russia',
  'Kazan, Russia',
  'Rostov-na-Donu, Russia',
  'Chelyabinsk, Russia',
  'Ufa, Russia',
  'Altona, Germany',
  'Nis, Serbia',
  'Porto, Portugal',
  'Kropyvnytskyi, Ukraine',
  'Kamianske, Ukraine',
  'Montpellier, France',
  'Czestochowa, Poland',
  'Saint Petersburg, Russia',
  'City of Westminster, United Kingdom',
  'Chemnitz, Germany',
  'Orsk, Russia',
  'Southampton, United Kingdom',
  'A Coruna, Spain',
  'Nizhnevartovsk, Russia',
  'Braunschweig, Germany',
  'Puente de Vallecas, Spain',
  'Angarsk, Russia',
  "Mar'ino, Russia",
  'Novorossiysk, Russia',
  'Khimki, Russia',
  'Blackpool, United Kingdom',
  'Krefeld, Germany',
  'Arhus, Denmark',
  'Kosice, Slovakia',
  'Chernivtsi, Ukraine',
  'Sant Marti, Spain',
  'Ternopil, Ukraine',
  'Gasteiz / Vitoria, Spain',
  'Yakutsk, Russia',
  'Granada, Spain',
  'Nizhnekamsk, Russia',
  'Halle (Saale), Germany',
  'Hamburg-Mitte, Germany',
  'Dzerzhinsk, Russia',
  'Kiel, Germany',
  'Bordeaux, France',
  'Gent, Belgium',
  'Syktyvkar, Russia',
  'Elche, Spain',
  'Milton Keynes, United Kingdom',
  'Magdeburg, Germany',
  'Ploiesti, Romania',
  'Lille, France',
  'Ciudad Lineal, Spain',
  'Bexley, United Kingdom',
  'Kremenchuk, Ukraine',
  'Sosnowiec, Poland',
  'Staryy Oskol, Russia',
  'Neue Neustadt, Germany',
  'Radom, Poland',
  'Groznyy, Russia',
  'Sector 1, Romania',
  'Oviedo, Spain',
  'Santa Cruz de Tenerife, Spain',
  'Graz, Austria',
  'Shakhty, Russia',
  'Blagoveshchensk, Russia',
  'Banja Luka, Bosnia and Herzegovina',
  'Babruysk, Belarus',
  'Fuencarral-El Pardo, Spain',
  'Messina, Italy',
  'Badalona, Spain',
  'Oberhausen, Germany',
  'Verona, Italy',
  "Prokop'yevsk, Russia",
  'Rybinsk, Russia',
  'Vykhino-Zhulebino, Russia',
  'Freiburg, Germany',
  'Northampton, United Kingdom',
  'Zelenograd, Russia',
  'Archway, United Kingdom',
  'Biysk, Russia',
  'Novi Sad, Serbia',
  'Velikiy Novgorod, Russia',
  'Centralniy, Russia',
  'Lutsk, Ukraine',
  'Bergen, Norway',
  'Braila, Romania',
  'Norwich, United Kingdom',
  'Mokotow, Poland',
  'Luebeck, Germany',
  'Cartagena, Spain',
  'Terrassa, Spain',
  'Eindhoven, Netherlands',
  'Rennes, France',
  'Torun, Poland',
  'Kielce, Poland',
  'Jerez de la Frontera, Spain',
  'Oradea, Romania',
  'Sabadell, Spain',
  'Mostoles, Spain',
  'Linz, Austria',
  'Alcala de Henares, Spain',
  'Ivano-Frankivsk, Ukraine',
  'Debrecen, Hungary',
  'Padova, Italy',
  'Erfurt, Germany',
  "Vasyl'evsky Ostrov, Russia",
  'Tampere, Finland',
  'Harburg, Germany',
  'Pskov, Russia',
  'Favoriten, Austria',
  'Nicosia, Cyprus',
  'Charleroi, Belgium',
  'Severnyy, Russia',
  'Tilburg, Netherlands',
  'Balakovo, Russia',
  'Armavir, Russia',
  'Bila Tserkva, Ukraine',
  'Dudley, United Kingdom',
  'Hagen, Germany',
  'Gliwice, Poland',
  'Pamplona, Spain',
  'Rostock, Germany',
  'Fuenlabrada, Spain',
  'Aberdeen, United Kingdom',
  'Reims, France',
  "Engel's, Russia",
  'Burgas, Bulgaria',
  'Kassel, Germany',
  'Severodvinsk, Russia',
  'Portsmouth, United Kingdom',
  'Newcastle upon Tyne, United Kingdom',
  'Klaipeda, Lithuania',
  'Zabrze, Poland',
  'Zlatoust, Russia',
  'Cork, Ireland',
  'Vantaa, Finland',
  "Syzran', Russia",
  'Bytom, Poland',
  'Almeria, Spain',
  'Praga Poludnie, Poland',
  'Sutton, United Kingdom',
  'Petropavlovsk-Kamchatsky, Russia',
  'Trieste, Italy',
  'Donaustadt, Austria',
  'Leganes, Spain',
  'Le Havre, France',
  'Swindon, United Kingdom',
  'Dun Laoghaire, Ireland',
  'San Sebastian, Spain',
  'Hamm, Germany',
  'Mainz, Germany',
  'Brescia, Italy',
  'Geneve, Switzerland',
  'Cergy-Pontoise, France',
  'Korolyov, Russia',
  'Sants-Montjuic, Spain',
  'Santander, Spain',
  'Liege, Belgium',
  "Kamensk-Ural'skiy, Russia",
  'Prato, Italy',
  'Saarbruecken, Germany',
  'Groningen, Netherlands',
  'Taranto, Italy',
  'Crawley, United Kingdom',
  'Castello de la Plana, Spain',
  'Yasenevo, Russia',
  'Podolsk, Russia',
  'Burgos, Spain',
  'Amadora, Portugal',
  'Ipswich, United Kingdom',
  'Bielsko-Biala, Poland',
  'Yuzhno-Sakhalinsk, Russia',
  'Almere Stad, Netherlands',
  'Split, Croatia',
  'Saint-Etienne, France',
  'Turku, Finland',
  'Wigan, United Kingdom',
  "Kramators'k, Ukraine",
  'Croydon, United Kingdom',
  'Miskolc, Hungary',
  'Walsall, United Kingdom',
  'Herne, Germany',
  'Lyublino, Russia',
  'Mansfield, United Kingdom',
  'Olsztyn, Poland',
  'Prizren, Kosovo',
  'Bacau, Romania',
  'Oxford, United Kingdom',
  'Muelheim, Germany',
  'Albacete, Spain',
  'Reggio Calabria, Italy',
  'Arad, Romania',
  'Baranovichi, Belarus',
  'Toulon, France',
  'Angers, France',
  'Horta-Guinardo, Spain',
  'Patra, Greece',
  'Alcorcon, Spain',
  'Berezniki, Russia',
  'Volgodonsk, Russia',
  'Breda, Netherlands',
  'Pitesti, Romania',
  'Miass, Russia',
  'Abakan, Russia',
  'Neukoelln, Germany',
  'Getafe, Spain',
  'Novocherkassk, Russia',
  'Osnabrueck, Germany',
  'Nou Barris, Spain',
  'Warrington, United Kingdom',
  'Szeged, Hungary',
  'Basel, Switzerland',
  'Zenica, Bosnia and Herzegovina',
  'Solingen, Germany',
  'Pilsen, Czech Republic',
  "Nazran', Russia",
  'Slough, United Kingdom',
  'Piraeus, Greece',
  'Bournemouth, United Kingdom',
  'Peterborough, United Kingdom',
  'Ludwigshafen am Rhein, Germany',
  'Floridsdorf, Austria',
  'Leverkusen, Germany',
  'Hortaleza, Spain',
  'Rubtsovsk, Russia',
  'Mytishchi, Russia',
  'Salavat, Russia',
  'Oldenburg, Germany',
  'Khoroshevo-Mnevniki, Russia',
  'Bibirevo, Russia',
  'Modena, Italy',
  'Nijmegen, Netherlands',
  'Grenoble, France',
  'Cambridge, United Kingdom',
  'Rzeszow, Poland',
  'Doncaster, United Kingdom',
  "Gol'yanovo, Russia",
  'Melitopol, Ukraine',
  'Admiralteisky, Russia',
  'San Blas-Canillejas, Spain',
  'Ussuriysk, Russia',
  'Tiraspol, Moldova',
];
